### ISSUE TITLE
Very unsafe Clone implementation over *mut u8

### ISSUE THREAD

**Issue by botika** [Kogia-sima/sailfish#10]
The amount of things that can happen here are endless. Basically I have the possibility of having two or more mutable pointers to the same place, imagine it in concurrency. Fortunately, `Send` has not been implemented, so it cannot be passed between threads, although that does not ensure disaster.
https://github.com/Kogia-sima/sailfish/blob/master/sailfish/src/runtime/buffer.rs#L13-L18

This is the prelude to the apocalypse:
```rust
#[derive(Clone)]
struct Any<T>(* mut T)
```
Edit: Sorry, yes, you implement Send:
```rust
   let buf = Buffer::with_capacity(32);
   let buf2 = buf.clone();
   let mut buf = buf.into_string();
   let j = spawn(move || write!(buf, "this"));
   let mut buf2 = buf2.into_string(); 
   write!(buf2, "or this");
   j.join().unwrap();
   println!("{}", buf2)
```
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=42d37db0830717872d53b14b48c28575

What do you see at your screen?

**Comment by Kogia-sima** [comment]
Thank you for pointing out my mistake! It is definitely a bug. I'll fix this soon.
