### ISSUE TITLE
Write null pointer

### ISSUE THREAD

**Issue by botika** [Kogia-sima/sailfish#11]
Is possible in the buffer implementation to write to null pointer.

```rust
let buf = Buffer::new();
buf.as_ptr_mut().write(1);
```

**Comment by Kogia-sima** [comment]
There is no guarentee that empty buffer points to valid heap memory. while it may be not exacly the same behaviour with `std::string::String`, there is no such a guarentee for `String` too. What you are doing is **Undefined behaviour**.

**Comment by botika** [comment]
Viewing `RawVec` imports and its structure. I highly doubt you can raise an exception for null pointer.
https://github.com/rust-lang/rust/blob/master/src/liballoc/raw_vec.rs#L8
However, other buffer implementations do the same without the ability to point to null.
https://github.com/tokio-rs/bytes/blob/master/src/bytes_mut.rs#L57
I think you shouldn't dedicate yourself to reinventing the wheel. Since I doubt that whatever you do you will overcome this buffer implementation. 

 I need hands to program. If you are interested, in Yarte I am working with WASM. I wouldn't matter to donate the project to a team to see it grow faster.
