### ISSUE TITLE
Deriving Send and Sync is unsafe

### ISSUE THREAD

**Issue by botika** [Kogia-sima/sailfish#15]
If you take a look at the Vec implementation of the rustonomicon. It seems essential to ensure the uniqueness of the pointer to be able to use it in other threads.

https://doc.rust-lang.org/nomicon/vec-layout.html

https://github.com/Kogia-sima/sailfish/blob/880cf9db5af79d8e74292d56bdf57089dacd8035/sailfish/src/runtime/buffer.rs#L100-L103

**Comment by Kogia-sima** [comment]
`u8` doesn't require drop. Also `Buffer` is an unique owner of the data, so it is completely safe.
