### ISSUE TITLE
Unsafe Vec::from_raw_parts

### ISSUE THREAD

**Issue by botika** [Kogia-sima/sailfish#16]
https://doc.rust-lang.org/std/vec/struct.Vec.html#method.from_raw_parts
### Safety
This is highly unsafe, due to the number of invariants that aren't checked:

- ptr needs to have been previously allocated via String / Vec <T> (at least, it's highly likely to be incorrect if it wasn't).

https://github.com/Kogia-sima/sailfish/blob/880cf9db5af79d8e74292d56bdf57089dacd8035/sailfish/src/runtime/buffer.rs#L102

**Comment by Kogia-sima** [comment]
There is no such a guarentee for String.

https://doc.rust-lang.org/std/string/struct.String.html#method.from_raw_parts
