### ISSUE TITLE
Update bench, please

### ISSUE THREAD

**Issue by botika** [Kogia-sima/sailfish#18]
It must be recognized that the implementation of itoa is very good, although it would have to be tested with large numbers. But as I said the buffer is not ok. I still have to go over things, but if you can update the results. Thank you :smile:

**Comment by Kogia-sima** [comment]
There is no significant performance improvement/depletion after last benchmark update.

Could you tell me why the buffer implementation is not ok?

**Comment by botika** [comment]
Sorry, just remove target directory and Cargo.lock. It's ~10us  better in big_table. `Sailfish` ~35us and `yarte Send` ~25us in my i7-7700HQ 2.8Ghz.

**Comment by Kogia-sima** [comment]
I've updated the benchmark results.

sailfish 0.1.1 is even faster than 0.1.0. However it seems that `Yarte` is sometimes a bit faster than sailfish.

**Comment by botika** [comment]
I just started
