### ISSUE TITLE
std::write! benchmark should escape to be an apples to apples comparison

### ISSUE THREAD

**Issue by udoprog** [Kogia-sima/sailfish#22]
One important thing sailfish does from a security perspective is process html-escapes for rendered values.

Since this is [not done for the `std::write!`](https://github.com/Kogia-sima/sailfish/blob/master/benches/src/std_write.rs#L69) the comparison is actually unfair in favor of `std::write!`. The `std::write!` values would need to be escaped for it to be fair, since this would add work.

**Comment by Kogia-sima** [comment]
@udoprog Thanks for the tips.

Used [v_htmlescape](https://docs.rs/v_htmlescape/0.10.0/v_htmlescape/) crate and updated the result. However no significant changes were detected.

**Comment by udoprog** [comment]
Thanks for looking into it!

One would probably need some data that requires escaping to note any difference, but that would mainly be comparing sailfish escapes and buffer management with `v_htmlescape`, which also seems to be fairly well optimized. But it's just a thought, and possibly contrived at that point. Thanks again!
