### ISSUE TITLE
Use correct configuration for yarte benches

### ISSUE THREAD

**Issue by botika** [Kogia-sima/sailfish#25]
For `Teams`, declare env var `CARGO_CFG_HTMLESCAPE_DISABLE_AUTO_SIMD` and warning you escape 2 less characters. 
Now I implement something unusable inline for the `buf-min::Buffer` trait. 

Update the Teams with that environment variable and commenting that your XSS countermeasures are lower.

Or leave me alone that between Askama, those who come from python and you have me happy. 
I'm working on a PHP substitution, not in python or Rust's default allocation algorithm replacements.

If you want to compete with someone, I recommend putting your buffer against the creators of `tokio-rs/bytes` to see what they think. Or do a PR to rust-lang for `RawVec` substitution or to TechEmpower benchmark.

**Comment by Kogia-sima** [comment]
(I am not very good at English, so I apologize in advance.)

> For Teams, declare env var CARGO_CFG_HTMLESCAPE_DISABLE_AUTO_SIMD and warning you escape 2 less characters.

I removed `Cargo.lock` and `target` directory, and then recompiled with `CARGO_CFG_HTMLESCAPE_DISABLE_AUTO_SIMD` variable. However I couldn't see any significant difference in the result.

> If you want to compete with someone, I recommend putting your buffer against the creators of tokio-rs/bytes to see what they think. Or do a PR to rust-lang for RawVec substitution or to TechEmpower benchmark.

Current buffer implementation is highly optimized for template rendering, and keeps compatibility with `std::string::String`. Also it is designed for performing well in Linux x86_64 platform specifically. Those concepts do not match to `BytesMut` nor `RawVec`. However it may be better to ask the opnion for `tokio` developpers. Thanks for the advice. :+1:

By the way, the Sailfish was initially developed as a tool for Rust teams in ISUCON (http://isucon.net/). ISUCON is a programming competition in Japan where participants compete for the performance of web applications. I'm going to compete with programmers who use another programming languages, so I keep research for faster web application until its perliminary contest, which is held in September.

> Or leave me alone that between Askama, those who come from python and you have me happy. I'm working on a PHP substitution, not in python or Rust's default allocation algorithm replacements.

I'm not willing to compete with passionate developers like you. Rather I would like to share the optimization techniques for building blazing fast web application.

**Comment by botika** [comment]
> By the way, the Sailfish was initially developed as a tool for Rust teams in ISUCON (http://isucon.net/). ISUCON is a programming competition in Japan where participants compete for the performance of web applications. I'm going to compete with programmers who use another programming languages, so I keep research for faster web application until its perliminary contest, which is held in September.

A million yen and I am poor! Great! And how do I sign up?

> > For Teams, declare env var CARGO_CFG_HTMLESCAPE_DISABLE_AUTO_SIMD and warning you escape 2 less characters.
> 
> I removed `Cargo.lock` and `target` directory, and then recompiled with `CARGO_CFG_HTMLESCAPE_DISABLE_AUTO_SIMD` variable. However I couldn't see any significant difference in the result.
> 
It may seem to me that with the iterator it goes a little slower than with the direct pointer, now I look at it.

> Current buffer implementation is highly optimized for template rendering, and keeps compatibility with `std::string::String`. Also it is designed for performing well on Linux x86_64 platform specifically. Those concepts do not match to `BytesMut` nor `RawVec`. However it may be better to ask the opnion for `tokio` developpers. Thanks for the advice. +1

Exactly, you could benchmark your buffer vs. another. 

> 
> > Or leave me alone that between Askama, those who come from python and you have me happy. I'm working on a PHP substitution, not in python or Rust's default allocation algorithm replacements.
> 
> I'm not willing to compete with passionate developers like you. Rather I would like to share the optimization techniques for building blazing fast web application.

Use `yarte` with your buffer taking advantage of `buf-min::Buffer` or a buffer like the one from the previous version, which was `bytes::BytesMut` + `&mut [MaybeUninit<u8>]` and as you already saw it worked faster. But I changed it because in `Techempower` it doesn't give the same result.

But the only change that affects the result, apart from the changes in `yarte`, is the escape algorithm. In this latest version you added an `if` for short cases, but the double table algorithm is exactly the same.

That is, I thought that seeing the previous results you would understand what was happening and it seems that you have not understood it.

**Comment by Kogia-sima** [comment]
> A million yen and I am poor! Great! And how do I sign up?

It has already stopped accepting applications because the limit was reached. However, It probably accepts more participants in August. Please keep track of the home page.

> Use yarte with your buffer taking advantage of buf-min::Buffer or a buffer like the one from the previous version, which was bytes::BytesMut + &mut [MaybeUninit<u8>] and as you already saw it worked faster.

Currently I'm discouraged because the Sailfish applies some another optimization that yarte does not apply. Let me know when Yarte performance will get faster than the Sailfish, with the detailed benchmark result.

Also, In ISUCON competition the participants is not allowed to track the database contents in advance. That means I cannot use [TemplateFixedTrait](https://docs.rs/yarte/0.12.0/yarte/trait.TemplateFixedTrait.html) because I don't know the maximum length of the rendered templates (and of course, `TemplateBytesTrait` will become somewhat slower).

Furthermore, now I believe the template engine has been already optimized enough. Recently I realized that the MySQL database connection API would be the biggest bottleneck. Because of this I would like to give priority to the development of the MySQL API (based on [mysql_async](https://github.com/blackbeam/mysql_async) crate) for a while.

> That is, I thought that seeing the previous results you would understand what was happening and it seems that you have not understood it.

Sorry, I don't know what you mean. Most programs in the world keep improving performance even after its stable release, doesn't it?

**Comment by botika** [comment]
> > That is, I thought that seeing the previous results you would understand what was happening and it seems that you have not understood it.
> 
> Sorry, I don't know what you mean. Most programs in the world keep improving performance even after its stable release, doesn't it?

I mean, the implementation with `BytesMut` +` &mut [MaybeUninit<u8>]` of` BigTable` was faster on these benchmarks than sailfish. You remember? https://github.com/Kogia-sima/sailfish/blob/933d7850d73795bf329a98797bc98228166276d3/benches/README.md#results 

And without any change in performance we move on to this.
https://github.com/Kogia-sima/sailfish/tree/a885f08d73dd32790874eebd1e935b90516ee552/benches#results
You win in `BigTable`. 
But what happens here? Because with this change I have a 2% more request in techempower and here I lose half? 

Then you enter an `if` for short cases in the escape algorithm. 
https://github.com/Kogia-sima/sailfish/tree/2807340e59ceacb30305428b9d3bd440e518fd16/benches#results
And you're already the fastest. 

But it seems to me that something is wrong.

> > Use yarte with your buffer taking advantage of buf-min::Buffer or a buffer like the one from the previous version, which was bytes::BytesMut + &mut [MaybeUninit] and as you already saw it worked faster.
> 
> Currently I'm discouraged because the Sailfish applies some another optimization that yarte does not apply. Let me know when Yarte performance will get faster than the Sailfish, with the detailed benchmark result.
> 

These optimizations you are talking about only exist in code like this, constant. And if you already have them, it depends on the **TRAIT** `buf-min::Buffer` on which any buffer can be implemented.

> Also, In ISUCON competition the participants is not allowed to track the database contents in advance. That means I cannot use [TemplateFixedTrait](https://docs.rs/yarte/0.12.0/yarte/trait.TemplateFixedTrait.html) because I don't know the maximum length of the rendered templates (and of course, `TemplateBytesTrait` will become somewhat slower).
> 

Ok, if I make an implementation on `TemplateBytesTrait`, (in commit https://github.com/botika/yarte/commit/a39f49d5e2f7826b1be492bca56cd79342369fe3) faster, will you be my sponsor with what you get from the prize?

**Comment by Kogia-sima** [comment]
> I mean, the implementation with BytesMut + &mut [MaybeUninit<u8>] of BigTable was faster on these benchmarks than sailfish.

`TemplateBytesTrait` was certainly faster but it was slower than old Sailfish in `Teams` benchmark. Note that the Sailfish 0.1.3 is faster than old version.

> And without any change in performance we move on to this.
> https://github.com/Kogia-sima/sailfish/tree/a885f08d73dd32790874eebd1e935b90516ee552/benches#results
> You win in BigTable.
> But what happens here? Because with this change I have a 2% more request in techempower and here I lose half?

I don't know what happened, but even if the benchmark is invalid, `TemplateFixedTrait` is not usable in ISUCON.

> These optimizations you are talking about only exist in code like this, constant. And if you already have them, it depends on the TRAIT buf-min::Buffer on which any buffer can be implemented.

Buffer implementation is only a part of the Sailfish runtime utilities. The entire code is composed of various optimizations such as [memcpy implementation for small length of bytes](https://github.com/Kogia-sima/sailfish/blob/master/sailfish/src/runtime/utils.rs).

> Ok, if I make an implementation on TemplateBytesTrait, (in commit botika/yarte@a39f49d) faster, will you be my sponsor with what you get from the prize?

Year I promise you :)

> And use https://github.com/fafhrd91/rust-postgres for sql.

Unfortunately, the ISUCON participants are forced to use a MySQL server, not a PostgresQL.

**Comment by Kogia-sima** [comment]
I'm going to close this issue anyway because `CARGO_CFG_HTMLESCAPE_DISABLE_AUTO_SIMD variable` variable has little effect on the performance.
