### ISSUE TITLE
Add fuzzing harness

### ISSUE THREAD

**Issue by ssokolow** [Kogia-sima/sailfish#26]
As I [mentioned](https://www.reddit.com/r/rust/comments/hnhbmv/sailfish_rusts_fastest_template_engine_200x/fxeexw6/) on the Reddit announcement thread, seeing 23 uses of the `unsafe` keyword in the GitHub repo search for a web app component that isn't being fuzzed makes me uneasy.

It'd probably be a good idea to get some fuzzing set up using something like [cargo-fuzz](https://github.com/rust-fuzz/cargo-fuzz), [afl.rs](https://github.com/rust-fuzz/afl.rs), or [honggfuzz-rs](https://github.com/rust-fuzz/honggfuzz-rs).

I'm having enough trouble just giving proper maintenance time to my own projects right now, so I can't be the one to do it but, if anyone else is interested, the [Rust Fuzz Book](https://rust-fuzz.github.io/book/) has an introduction to cargo-fuzz and the beginnings of one for afl.rs.

**Comment by Kogia-sima** [comment]
@ssokolow Thanks for the tips! Fuzzing is known as one of the method to improve test coverage. Currently sailfish repository has 32 `unsafe` blocks or functions in total, so it seems to be good to add fuzzing tests.

I want to work on this. Please wait for a while because It requires for `sailfish-compiler` to export some APIs.

**Comment by ssokolow** [comment]
> Thanks for the tips!
Glad I could help.

> Fuzzing is known as one of the method to improve test coverage.
A way to discover new things to test, maybe, but I'm not sure I'd consider it a way to improve test coverage, given that fuzzing isn't the kind of thing you'd run as part of your CI runs.

That's more what [property testing](https://lib.rs/crates/proptest) is for.

> I want to work on this. Please wait for a while because It requires for `sailfish-compiler` to export some APIs.

No problem. I'm far too familiar with "I want to do this, but it'll take a while".
