### ISSUE TITLE
Consider add random lenght benchmark

### ISSUE THREAD

**Issue by botika** [Kogia-sima/sailfish#28]
I was looking at the implementation of size_hint. If it's always the same, that's fine. 

https://github.com/Kogia-sima/sailfish/blob/119e282945ee1c0b2d9083a3d615dee09125ac89/sailfish-compiler/src/procmacro.rs#L278-L284

Better an ONCE-like implementation, sure to give better results. 

Seriously take the above measurement and update all threads by a single `AtomicUsize`. 
Well I'm looking forward to seeing it up and running with all those stars of people with so much experience.

**Comment by Kogia-sima** [comment]
Here is the benchmark result of malloc + free operation (glibc 2.31 for amd64 arch).

![results](https://user-images.githubusercontent.com/20660712/88061011-eb88b680-cba1-11ea-8a60-617f4718edcd.png)

As you can see, 100kB allocation is as fast as 5kB allocation. Also 0kB allocation takes 75ns on average. That means, 100kB allocation is faster than two small allocations.

I believe such a benchmark doesn't make sense, because over size preallocation is always faster than a bunch of small allocations.

**Comment by botika** [comment]
But common situation, the first measures n the second n / 2, the third n * 3, etc. I insist on trying it in some situation where the size is not constant.

**Comment by Kogia-sima** [comment]
How would it be a bottleneck? Even if the rendered size is randomized, the size hint will converge on its maximum size. After convergence, the memory is allocated only once per rendering, and never reallocate the memory.

Could you explain the situation where the current implementation becomes a bottleneck more concretely?

**Comment by botika** [comment]
https://llvm.org/docs/Atomics.html#acquire
Acquire provides a barrier of the sort necessary to acquire a **lock** to access other memory with normal loads and stores.
https://llvm.org/docs/Atomics.html#release
Release is similar to Acquire, but with a barrier of the sort necessary to release a **lock**.

**Comment by Kogia-sima** [comment]
That "lock" implies the atomic fence, which is not related to the lock system provided by OS (such as mutex).

https://www.codeproject.com/Articles/1183423/We-Make-a-std-shared-mutex-10-Times-Faster

For a simple read/write operation, atomic fence prevent compilers to:

1. optimize some arithmetic calculations at compile time
2. reorder the instructions specified in IR
3. place its variable at specific memory location

Program does not wait until the write operation. Hence this would not become a bottleneck,  even in a multithreaded application.

**Comment by Kogia-sima** [comment]
Note that on the x86_64 system the atomic operations will be transformed into simple 'mov' instruction. (https://github.com/Kogia-sima/sailfish/issues/24#issue-654698709)

**Comment by botika** [comment]
Well if I don't convince you with this you can always try https://github.com/botika/bytes/tree/alloc buffer implementation. I'm thinking about the text of the sponsor tier.

**Comment by Kogia-sima** [comment]
I've removed the benchmark in favor of https://github.com/djc/template-benchmarks-rs. If you have any complaint about benchmarks, please re-create an issue on the djc's repository.

**Comment by botika** [comment]
But djc has blocked me, I can't make issues or PR to their repositories. How do I do it?
