### ISSUE TITLE
Bad use of Reference Counter

### ISSUE THREAD

**Issue by botika** [Kogia-sima/sailfish#35]
Normally when the Rust lifetimes are not known this is usually done. A normal reference when used will give the same result. 

https://github.com/Kogia-sima/sailfish/blob/834289be5914a0a67ff8bb020602180fff9d048d/sailfish-compiler/src/parser.rs#L100
https://doc.rust-lang.org/std/rc/struct.Rc.html

**Comment by Kogia-sima** [comment]
I don't know what you mean, but I strongly believe that the excerpt code is not a "Bad" usage of `Rc`.

First, `Rc`/`Arc` works as a marker of immutability. `Rc` implements `Deref` but not `DerefMut`, thus these containers avoid accidental mutation of the inner data.

Second, `Rc` reduces the cost of clone. Thanks to reference counter, the assembly results in only 1 or 3  instructions for cloning of `block_delimiter`. If it is not wrapped, assembly results in two memory allocation and two memcpy function call.

Third, `Rc` sometimes reduces the type size. Well, in fact the `block_delimiter` was initially wrapped by `SmallVec`. The size of the type wrapped by SmallVec tend to be very large. In contrast, `Rc` always results in 8 byte.

For these reasons, unwrapping `Rc` from the `block_delimiter` field is highly discouraged and not fixed.

**Comment by botika** [comment]
I think this is useful for something, surely you know it.
```rust
#[derive(Clone, Debug)]
pub struct ParseStream<'a, 'b> {
    block_delimiter: (&'b str, &'b str),
    pub(crate) original_source: &'a str,
    source: &'a str,
    delimiter: char,
}
```
