### ISSUE TITLE
Delete yarte benchmarks

### ISSUE THREAD

**Issue by botika** [Kogia-sima/sailfish#36]
As I explained to you, the benchmarks are wrong, if you want to compete with you, the environment must be the Techempower. If not, please remove it as it creates confusion.

### The only benchmarks that work well are those from Techempower. This goes for any other benchmark.

**Comment by Kogia-sima** [comment]
> the benchmarks are wrong

No. As I explained.

https://github.com/Kogia-sima/sailfish/issues/28

This issue is still labelled as "Need More Info". If you think the benchmark is wrong, The best way to complain is to make things and show me the evidences.

**Comment by Kogia-sima** [comment]
closes in favor of #28
