### ISSUE TITLE
Please remove yarte from your benchmarks and put your implementation in Techempower

### ISSUE THREAD

**Issue by botika** [Kogia-sima/sailfish#37]
The only benchmarks that I consider reliable are Techempower. 

**Please if you want to compete with yarte please do your PR to Techempower.** 

[TechEmpower Benchmark Reference](https://github.com/TechEmpower/FrameworkBenchmarks/pull/6168#issuecomment-744060298), if you want to pass them on to the askama to delete me too that has blocked me.

**Comment by Kogia-sima** [comment]
There isn't enough reason to remove yarte benchmark. The benchmark in this repository compare the performance of simply rendering templates, while Techempower measures the performance of total response time (including SQL connections).

**Comment by Kogia-sima** [comment]
Steps to deploy Sailfish to Techempower:

- [ ] Add tests for Techempower benchmark
- [ ] Release v0.3.0

**Comment by botika** [comment]
For these benchmarks to be somewhat reliable, you would have to:
- use the proc_macro `ywrite_html` with an implementation of `buf-min` based on `Vec<u8>` or something similar
-  `CARGO_CFG_HTMLESCAPE_DISABLE_AUTO_SIMD` environment variable  should also be set
- enjoy

In this link to the comment of the PR to TechEmpower what I wanted to show you is the difference between `markup` and` yarte` with the `bytes-buf` feature. 

I think that if you upload it to where `yarte` is and it turns out that it gives more requests per second, I can say goodbye to these benchmarks.
That I have not paid anyone, this has been merged by their respective owners. You can use the same implementation, I think they will be very happy that it goes faster.

**Comment by botika** [comment]
Thanks a lot! If you can tell the `askama` who's got me blocked, please. 
If I've told you about Techempower it's because I've seen it before, good luck!
