### ISSUE TITLE
Escape algorithm is broken MIT or Apache Licence 

### ISSUE THREAD

**Issue by botika** [Kogia-sima/sailfish#39]
The escape algorithm, minus the mask which is for different values, the entire search and replace vectorization algorithm  is a line by line copy of `v_escape`, using exactly the same method to iterate over the mask, false positives, double static table, which never had been done and is the main part of yarte. 

I don't normally do this, **but democracy in science forces me**.

If you want to use my algorithm to beat me in the benchmarks, at least mention me in a comment, it would be a detail on your part. 

**Or you can do as askama use my optimized code and tell me that I have copied it.**

**Comment by Kogia-sima** [comment]
I don't know about the internal algorithm used in `v_escape`, so I'm sorry that my comment might not get the point.

I think that if someone try to write the algorithm for HTML escaping using SIMD intrinsics, then it'll always results in similar code, won't it? Those algorithm would read 32 bytes, check if any of those characters, and check each bytes based on look-up-table if escape is needed. Is there a way to implement HTML escape using SIMD intrinsics?

My implementation is inspired by [rust-memchr](https://github.com/BurntSushi/rust-memchr) crate, which also uses "vector mask" and "entire search" algorithm.

Also You can see that my implementation have been updated many times. Those changes were mainly because the first implementation was not optimized and had many security issues.

I am saying the same thing again, but if you have any complaint about this crate, what you should do is to provide a concrete example or some pertinent evidence with it.

**Comment by botika** [comment]
What a coincidence like me! I also took memchr as a reference, the strange thing is that I do not see the alignment or the passes of 1024bits.
**Prove A**: Launch `cargo expand` in https://github.com/botika/v_escape/tree/master/v_htmlescape
Line 411:
```rust
static V_ESCAPE_TABLE: [u8; 256] = [
    6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
    6, 6, 0, 6, 6, 6, 1, 2, 6, 6, 6, 6, 6, 6, 6, 3, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 4, 6, 5, 6,
    6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
    6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
    6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
    6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
    6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
    6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
];
static V_ESCAPE_QUOTES: [&str; 6] = ["&quot;", "&amp;", "&#x27;", "&#x2f;", "&lt;", "&gt;"];
const V_ESCAPE_LEN: usize = 6;
```

Line 876:
Removing debug_asserts
```rust
if mask != 0 {
                            {
                                let at = {
                                    ...
                                    (ptr as usize) - (start_ptr as usize)
                                };
                                let mut cur = mask.trailing_zeros() as usize;
                                loop {
                                    let c = {
                                        unsafe {
                                            *V_ESCAPE_TABLE.as_ptr().add(*ptr.add(cur) as usize)
                                        }
                                    } as usize;
                                    if c < V_ESCAPE_LEN {
                                        {
                                            let i = at + cur;
                                            {
                                                if start < i {
                                                    #[allow(unused_unsafe)]
                                                    fmt.write_str(unsafe {
                                                        std::str::from_utf8_unchecked(
                                                            &bytes[start..i],
                                                        )
                                                    })?;
                                                }
                                                fmt.write_str({
                                                    unsafe { *V_ESCAPE_QUOTES.as_ptr().add(c) }
                                                })?;
                                                start = i + 1;
                                            };
                                        };
                                    };
                                    mask ^= 1 << cur;
                                    if mask == 0 {
                                        break;
                                    }
                                    cur = mask.trailing_zeros() as usize;
                                }
                                ...
                                }
                            };
                        }
                        ptr = ptr.add(M128_VECTOR_SIZE);
                    }
```
Line 889:
And the corpse
```rust
                                  loop {
                                    let c = {
                                        unsafe {
                                            *V_ESCAPE_TABLE.as_ptr().add(*ptr.add(cur) as usize)
                                        }
                                    } as usize;
                                    if c < V_ESCAPE_LEN {
                                        {
                                            let i = at + cur;
                                            {
                                                if start < i {
                                                    #[allow(unused_unsafe)]
                                                    fmt.write_str(unsafe {
                                                        std::str::from_utf8_unchecked(
                                                            &bytes[start..i],
                                                        )
                                                    })?;
                                                }
                                                fmt.write_str({
                                                    unsafe { *V_ESCAPE_QUOTES.as_ptr().add(c) }
                                                })?;
                                                start = i + 1;
                                            };
                                        };
                                    };
                                    mask ^= 1 << cur;
                                    if mask == 0 {
                                        break;
                                    }
                                    cur = mask.trailing_zeros() as usize;
                                }
                           
```

**Comment by Kogia-sima** [comment]
I'll admit that both look-up-table tables look like somewhat similar, but it is a very common style of LUT table. You can easily find similar strategy elsewhere (e.g. [here](https://github.com/k0kubun/hescape/blob/master/hescape.c) and [here](https://benchmarksgame-team.pages.debian.net/benchmarksgame/program/revcomp-rust-1.html))

And about Line 876, I believe it is hard to say "sailfish implementation is a copy of v_escape implementation". It is true that sailfish uses similar algorithm, but it is written in pointer-based operation. Also logic structure is completely different.

```rust
// sailfish implementation

while mask != 0 {
    let trailing_zeros = mask.trailing_zeros() as usize;
    mask ^= 1 << trailing_zeros;
    let ptr2 = ptr.add(trailing_zeros);
    let c = ESCAPE_LUT[*ptr2 as usize] as usize;
    if c < ESCAPED_LEN {
        if start_ptr < ptr2 {
            let slc = slice::from_raw_parts(
                start_ptr,
                ptr2 as usize - start_ptr as usize,
            );
            buffer.push_str(std::str::from_utf8_unchecked(slc));
        }
        push_escaped_str(*ESCAPED.get_unchecked(c), buffer);
        start_ptr = ptr2.add(1);
    }
}
```

**Comment by botika** [comment]
And hescape exactly where the line is that does the same thing because I'm freaking out with you. 

Give me the exact line. And explain to me the difference between the while and loop.

**Comment by Kogia-sima** [comment]
I investigated what `v_escape` generates using [cargo-expand](https://github.com/dtolnay/cargo-expand). It seems that `sailfish` and `v_escape` uses completely different algorithm from macro perspective.

* Sailfish creates "fast path" for the sequence shorter than 16 bytes, and for the fast path buffer will be pre-allocated
* HTML escaping in sailfish is consistently written in pointer-based strategy, while `v_escape` somewhat uses index-based approach
* algorithm for generating mask is completely different. Sailfish uses `OR => EQUAL` manipulation, but `v_escape` uses the range optimization
* Sailfish directly calls `avx2::escape` when compiled with avx feature.
* `v_escape` also searches aligned position and use `_mm256_load_si256` for faster loading, which sailfish does not.
* `v_escape` load 256 bytes if the sequence is so long, and process them at once, which `sailfish` does not.
* Sailfish uses `push_escaped_str` for writing escaped string, which `v_escape` does not.
* `v_htmlescape` escapes 6 characters, while `sailfish` escapes 5 characters.

**Comment by Kogia-sima** [comment]
> Explain the differences, except for the mask, between your algorithm and mine? And put it in an article.

so you mean you own copyright for your "algorithm" itself? It's not that sailfish implementation derives from `v_escape` crate, but I think you misunderstand something about copyright.

Algorithm used in the program is, at least under the Copyright Act in Japan, not copyrightable (著作権法第10条1項). You only have copyrights for your source code, and not for your algorithm. If you don't want your algorithm to be protected, you must obtain the software patent for its algorithms. You can also manually specify your copyright for the algorithm if your license supports.

I don't know what country you live, but I heard many countries follow this rule. You are not supposed to have any copyrights for the algorithm used in `v_escape`.

MIT License states that the copyright and permission notice shall be included in all copies and software, but does not mention about the algorithm used in the software. That means the restriction for the algorithm simply derives from the copyright law.

And I said before, but algorithm used here is quite simple and when someone write the HTML escape algorithm using SIMD intrinsics, many people easily come up with the algorithm used here. It just do the same thing as [askama](https://github.com/djc/askama/blob/b880799c31ddae53be242c6511794f5d7d35de6e/askama_escape/src/lib.rs#L100-L138) except that it checks 8/16 bytes simultaneously.

So, even if sailfish uses same algorithm used in `v_escape`, the is no copyright issue here.

**Comment by botika** [comment]
The askama escape is mine, see commits. 

If I understand, you can copy the code and screw me. Good luck with the new code.

**Comment by botika** [comment]
https://github.com/djc/askama/pull/152 Look how he thanked me for the escape, that rat, after 36 Pull request https://github.com/djc/askama/pulls?q=is%3Apr+is%3Aclosed+author%3Abotika

In the end I will have to thank you. I've already seen how this works.

**Comment by Kogia-sima** [comment]
> If I understand, you can copy the code and screw me

FYI: you can not apply your own copyrights for the copies of source code protected by license. Also you must ensure that any software patent does not exist for its software and its license does not specify any restrictions for algorithms.

**Comment by botika** [comment]
It is very clear, I have already understood, that you are right and I am not. Thank you very much for explaining it to me.
