### ISSUE TITLE
Missing template results in `stable/nightly mismatch` error

### ISSUE THREAD

**Issue by d4h0** [Kogia-sima/sailfish#50]
Hi,

I finally had an opportunity to give `sailfish` a try, and I ran into a problem.

I had this code:

```rust
#[derive(TemplateOnce)]
#[template(path = "layouts/base.stpl")]
struct BaseLayout {}
```

...and running it, resulted in the following error:

```
error: proc-macro derive panicked
  --> ssg/src/main.rs:16:10
   |
16 | #[derive(TemplateOnce)]
   |          ^^^^^^^^^^^^
   |
   = help: message: stable/nightly mismatch
```

The problem was, that "layouts/base.stpl" didn't exist (I had forgotten to rename the template).

Because of the error message, I didn't think my templates could be the problem, and therefore it took me some time to figure out what was going on.

Would it be possible to improve the error message?

**Comment by Kogia-sima** [comment]
Hmm... that's strange. I think sailfish-compiler should print an error message for missing files.

https://github.com/Kogia-sima/sailfish/blob/5209876df41ce9d765fc4422d16137b96807d267/sailfish-compiler/src/procmacro.rs#L174-L186

I'll examine this when I get home.

**Comment by d4h0** [comment]
The strange this is, in the beginning, I saw the above error message ("Template file {:?} not found") in VSCode. But later I only got the error message, that I reported above.

**Comment by d4h0** [comment]
Even more strange, I wanted to post a snipped that reproduces the error, but now I get the proper error again (in VSCode, and in the terminal). I don't remember that I changed anything significant, but it seems I did.

I'll close this now, and re-open it, if I get the initially reported error again.

You can see the error message that I copied from my terminal above, so I clearly didn't imagine it, but now I can't reproduce it (and I still had the original code that triggered the error).

**Comment by Kogia-sima** [comment]
@dh40 Thank you for your investigation. I added a [test](https://github.com/Kogia-sima/sailfish/commit/5c5c57f4377d9e4ab29b455ff16054d64426a44d) for this but still can't reproduce the error.

**Comment by d4h0** [comment]
I managed to reproduce it:

```rust
use sailfish::TemplateOnce;

#[derive(TemplateOnce)]
#[template(path = "layouts/article.stpl")]
struct Article {}

impl Article {
    fn new() -> Self {
        Self {}
    }
}

#[derive(TemplateOnce)]
#[template(path = "pages/test.stpl")]
struct TestPage {
    foo: String,
    bar: String,
}

fn main() {
    dbg!(TestPage {
        foo: "foo".into(),
        bar: "bar".into(),
    }
    .render_once()
    .unwrap());
}
```

"layouts/article.stpl" exists, however "pages/test.stpl" does not exist.

If I remove the following code, I get the proper error message ("Template file {:?} not found"):

```rust
#[derive(TemplateOnce)]
#[template(path = "layouts/article.stpl")]
struct Article {}

impl Article {
    fn new() -> Self {
        Self {}
    }
}
```

Are you able to reproduce this?

**Comment by Kogia-sima** [comment]
Ok. I reproduced it. It seems this error comes from invalid usage of `proc_macro2` private API. I fixed the compiler implementation to avoid this.

* before

```console
error: proc-macro derive panicked
  --> src/main.rs:14:10
   |
14 | #[derive(TemplateOnce)]
   |          ^^^^^^^^^^^^
   |
   = help: message: stable/nightly mismatch
```

* affter

```console
error: Template file "pages/test.stpl" not found
  --> src/main.rs:15:19
   |
15 | #[template(path = "pages/test.stpl")]
   |                   ^^^^^^^^^^^^^^^^^
```

**Comment by d4h0** [comment]
That's great, thank you!
