### ISSUE TITLE
Feature: Allow using templates defined as consts.

### ISSUE THREAD

**Issue by wojciechkepka** [Kogia-sima/sailfish#54]
For example I'd like to define a template as a const variable and use the derive macro to specify the name of the variable.

```rust
use sailfish::TemplateOnce;

const HTML:  &[u8] = br#"
<html>
<head> <% head %> </head>
</html>"#;

#[derive(TemplateOnce)]
#[template(var = HTML)]
struct HtmlContext {
    head: String,
}
```

**Comment by Kogia-sima** [comment]
This isn't possible because procedural macros are processed at parsing phase which precedes the semantic analysis phase. In other words procedural macro never know actual content of const variable.

**Comment by wojciechkepka** [comment]
Makes sense, thanks for the response!

**Comment by d4h0** [comment]
@Kogia-sima: Would the following be possible?

```rust
use sailfish::TemplateOnce;

#[derive(TemplateOnce)]
#[template(text = br#"
  <html>
  <head> <% head %> </head>
  </html>
"#)]
struct HtmlContext {
    head: String,
}
```

I have seen other template engines that do it like this.

**Comment by wojciechkepka** [comment]
I think that would work. My use case is to define test structs that derive TemplateOnce with small enough templates that it doesn’t make sense to make a file for each case.

**Comment by wojciechkepka** [comment]
For what it's worth I think it's actually possible to pass a const value as an attribute. At lest `clap` somehow handles it.

This compiles so it would be possible to do the same for `sailfish`.
```rust
const HELP: &str = "";

#[derive(Clap)]
#[clap(version = "0.1.0", author = "Wojciech Kępka <wojciech@wkepka.dev>", about = HELP)]
```

**Comment by Kogia-sima** [comment]
@wojciechkepka sailfish template must be parsed at compile time, though clap attribute argument will be parsed at runtime. Sailfish and Clap uses completely different approach, which makes impossible to pass const variable to sailfish derive macros.

**Comment by wojciechkepka** [comment]
Ok, thanks for the answer :) I no longer need it anyways just thought it might be possible.

**Comment by Kogia-sima** [comment]
@d4h0 Thanks for your suggestion. Passing string literals looks like feasible idea. For now I'm overwhelmed at work so It may take long time. I'll accept any PR to improve sailfish template engine.
