### ISSUE TITLE
Syntax(vim): `<` and `>` are incorrectly highlighted in opening and closing tags.

### ISSUE THREAD

**Issue by wojciechkepka** [Kogia-sima/sailfish#56]
Tested with multiple themes like `morhetz/gruvbox`, `ayu-theme/ayu-vim`. 

```
❯ nvim --version
NVIM v0.4.4
```

![image](https://user-images.githubusercontent.com/46892771/107849314-da7feb00-6dfa-11eb-890b-b0829bfeadb3.png)
![image](https://user-images.githubusercontent.com/46892771/107849280-85dc7000-6dfa-11eb-8879-6e9205ed3a7b.png)

**Comment by Kogia-sima** [comment]
Hmm, It seems this happened due to unneeded `contained` option added in https://github.com/Kogia-sima/sailfish/commit/a3fdc8e226b15f237491e61fba141d7b4e7a4113, but still don't know why Vim highlighted these tags as `htmlError`. I removed this for workaround, but something strange happens here.

**Comment by Kogia-sima** [comment]
## Before

![previous_highlight](https://user-images.githubusercontent.com/20660712/107854567-06818780-6e60-11eb-9629-41bc57d68b92.png)

## After

![new_highlight](https://user-images.githubusercontent.com/20660712/107854573-15683a00-6e60-11eb-9fc9-7c3d86a026b9.png)

**Comment by wojciechkepka** [comment]
Can confirm that 1857aea fixed the issues, thanks :)

**Comment by wojciechkepka** [comment]
Perhaps you wanted to investigate further after reading your comment for the second time so I'll reopen.

**Comment by Kogia-sima** [comment]
Oh, that was obvious. My redefinition of `htmlTag` group explicitly ignores the tag starts with `<%` in order to avoid syntax collision. If `sailfishBlock` rules fail to match `<%`, that tag falls back to `htmlError`, which matches `[<>&]`.
