### ISSUE TITLE
Possible XSS in html 

### ISSUE THREAD

**Issue by botika** [Kogia-sima/sailfish#7]
I think you are missing characters to escape.
```rust
const ESCAPED: [&str; 4] = ["&quot;", "&amp;", "&lt;", "&gt;"];
```
https://github.com/Kogia-sima/sailfish/blob/master/sailfish/src/runtime/escape/mod.rs#L25
 Anyway, you could specify it in the benchmarks.

**Comment by Kogia-sima** [comment]
There seems to be a difference between what characters should be escaped in HTML and in JavaScript. Currently I'm planning to implement multiple escapers and serves the utility to change the current escaper.

Anyway, current implementation is somewhat based on [Maud](https://github.com/lambda-fairy/maud) and maud escapes only these four characters. Sorry for not documenting this, but I think thse characters are sufficient to escape a plane HTML.
