### ISSUE TITLE
Double alloc chars

### ISSUE THREAD

**Issue by botika** [Kogia-sima/sailfish#8]
I think this could remove the `buf` and have an implement `AsMut <[u8]>` for `Buffer`. 

https://github.com/Kogia-sima/sailfish/blob/master/sailfish/src/runtime/buffer.rs#L124-L125

I think it would go a little faster.

**Comment by Kogia-sima** [comment]
I know that, but this is not a hotspot. Since sailfish is immature library there are some coldspots that stilll not optimized. If you want to optimize these implementations, feel free to create a new PR.
